language: node_js
node_js:
  - node
git:
  depth: false
jobs:
  include:
    - stage: test
      script: 
        - yarn install --pure-lockfile
        - yarn build
        - yarn test
        - yarn coverage
    - stage: deploy
      script:
        - yarn install --pure-lockfile
        - yarn build
        - bash scripts/deploy.sh
stages:
  - name: test
    if: (type = pull_request) OR ((type = push) AND (branch = master))
  - name: deploy
    if: (type = push) AND (branch = master)
